### ISSUE TITLE
Proxy assets server not working properly

### ISSUE THREAD

**Issue by turboMaCk** [half-pipe/half-pipe#98]
Hi,
Yesterday i tested half-pipe on one of my projects which running **rails 4.1.1** and I have problem with grunt-connect-proxy configuration. **Asset's static server return 404 on main.css** but the file was right in place.

I fixed it by removing assets and let it proxy to rails which handle assets loading correctly:

```
// remove this line on line 32
var assetServer = connect['static'](options.base[0]);

// remove this from condition starting on line 41
 if(request.url.match(/^\/assets/) && 1 == 4) {
    return assetServer;
  }
```

Why are you to handling assets get in node.js insted of rails? Can I do pull request which fix this bug this way (by removing assets static server from connect)??

**Comment by joefiorini** [comment]
We're handling the assets in node because it's a different build than the production build. It is much simpler to have a single process watching, building and serving the assets than to separate them out. It's also easier for a front-end developer familiar with Grunt to configure the server there than to expect them to figure out the rails way of configuring everything. You could always do `grunt build:public`, set `config.serve_static_assets = true` in `config/environments/development.rb` and serve the public assets through Rails.

 In a future release, this will all be handled by broccoli, which integrates the watching, building & serving for us.

**Comment by joefiorini** [comment]
Leaving this open until I get a chance to try reproducing it.

**Comment by turboMaCk** [comment]
Sure but if I looked in sass task's option setting is designed to work only with main.scss.

```
debug: {
  src: '<%%= dirs.tmp %>/prepare/assets/styles/main.scss',
  dest: '<%%= dirs.tmp %>/public/assets/styles/main.css'
  options: {
    style: 'expanded'
  }
},
```

Require.js works almost the same way. So the debug build output is (almost) same as production build. 

Grunt task will always work and you can handle every task by grunt and just let rails load files. I thing that current solution still can't handle different build output for production and dev environment.

With Grunt I often use **grunt-html-build** for having files separate in dev and merging them in production but I thing that this have to be handle in Rails in this case.

I'll test this little bit more.

**Comment by turboMaCk** [comment]
Got it. Problem is only with my custom compass setup. With sass it works fine on the same project so this is not bug in gem.
